"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class contact_kalman_lcmt(object):
    __slots__ = ["pc_f", "pc_z", "pc_phi", "x_est", "z_force_est", "z_force_sim"]

    __typenames__ = ["float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[4], [4], [4], [4], [4], [4]]

    def __init__(self):
        self.pc_f = [ 0.0 for dim0 in range(4) ]
        self.pc_z = [ 0.0 for dim0 in range(4) ]
        self.pc_phi = [ 0.0 for dim0 in range(4) ]
        self.x_est = [ 0.0 for dim0 in range(4) ]
        self.z_force_est = [ 0.0 for dim0 in range(4) ]
        self.z_force_sim = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(contact_kalman_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.pc_f[:4]))
        buf.write(struct.pack('>4f', *self.pc_z[:4]))
        buf.write(struct.pack('>4f', *self.pc_phi[:4]))
        buf.write(struct.pack('>4f', *self.x_est[:4]))
        buf.write(struct.pack('>4f', *self.z_force_est[:4]))
        buf.write(struct.pack('>4f', *self.z_force_sim[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != contact_kalman_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return contact_kalman_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = contact_kalman_lcmt()
        self.pc_f = struct.unpack('>4f', buf.read(16))
        self.pc_z = struct.unpack('>4f', buf.read(16))
        self.pc_phi = struct.unpack('>4f', buf.read(16))
        self.x_est = struct.unpack('>4f', buf.read(16))
        self.z_force_est = struct.unpack('>4f', buf.read(16))
        self.z_force_sim = struct.unpack('>4f', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if contact_kalman_lcmt in parents: return 0
        tmphash = (0x94a745dc578e75b9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if contact_kalman_lcmt._packed_fingerprint is None:
            contact_kalman_lcmt._packed_fingerprint = struct.pack(">Q", contact_kalman_lcmt._get_hash_recursive([]))
        return contact_kalman_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", contact_kalman_lcmt._get_packed_fingerprint())[0]

