"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class parameter_list_update_request_lcmt(object):
    __slots__ = ["requestNumber", "requestKind"]

    __typenames__ = ["int64_t", "int8_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.requestNumber = 0
        self.requestKind = 0

    def encode(self):
        buf = BytesIO()
        buf.write(parameter_list_update_request_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.requestNumber, self.requestKind))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != parameter_list_update_request_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return parameter_list_update_request_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = parameter_list_update_request_lcmt()
        self.requestNumber, self.requestKind = struct.unpack(">qb", buf.read(9))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if parameter_list_update_request_lcmt in parents: return 0
        tmphash = (0xe586645395a2713d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if parameter_list_update_request_lcmt._packed_fingerprint is None:
            parameter_list_update_request_lcmt._packed_fingerprint = struct.pack(">Q", parameter_list_update_request_lcmt._get_hash_recursive([]))
        return parameter_list_update_request_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", parameter_list_update_request_lcmt._get_packed_fingerprint())[0]

